project_id = "kvuiqexsovexuyfgztwk"

[functions.convert-document]
verify_jwt = false

[functions.pdf-operations]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.process-paypal-payment]
verify_jwt = false

[functions.send-converted-document]
verify_jwt = false

[functions.send-login-credentials]
verify_jwt = false
