// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-supported-formats.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var MODULES = {
  documents: {
    label: "Dokumenti",
    formats: ["pdf", "docx", "doc", "odt", "rtf", "txt", "html", "md"]
  },
  spreadsheets: {
    label: "Tabele",
    formats: ["xlsx", "xls", "ods", "csv", "tsv"]
  },
  presentations: {
    label: "Prezentacije",
    formats: ["pptx", "ppt", "odp", "pdf"]
  },
  images: {
    label: "Slike",
    formats: ["jpg", "jpeg", "png", "webp", "gif", "bmp", "tiff", "svg", "ico", "heic"]
  },
  audio: {
    label: "Audio",
    formats: ["mp3", "wav", "ogg", "m4a", "aac", "flac"]
  },
  video: {
    label: "Video",
    formats: ["mp4", "webm", "mov", "avi", "mkv", "gif"]
  }
};
var list_supported_formats_default = defineTool({
  name: "list_supported_formats",
  title: "List supported conversion formats",
  description: "Returns the categories of files BH KONVER can convert (documents, spreadsheets, presentations, images, audio, video) and the file extensions each category supports.",
  inputSchema: {
    module: z.enum([
      "documents",
      "spreadsheets",
      "presentations",
      "images",
      "audio",
      "video"
    ]).optional().describe("Optional. Restrict result to a single module.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ module }) => {
    const payload = module ? { [module]: MODULES[module] } : MODULES;
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { modules: payload }
    };
  }
});

// src/lib/mcp/tools/get-pricing-plans.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var PLANS = [
  { id: "24h", label: "24 sata", price_bam: "2.00", duration: "1 dan" },
  { id: "48h", label: "48 sati", price_bam: "10.00", duration: "2 dana" },
  {
    id: "monthly",
    label: "Mjese\u010Dna pretplata",
    price_bam: "20.00",
    duration: "30 dana"
  }
];
var get_pricing_plans_default = defineTool2({
  name: "get_pricing_plans",
  title: "Get BH KONVER pricing plans",
  description: "Returns available BH KONVER premium subscription plans with duration and price in BAM (billed in EUR via PayPal).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PLANS, null, 2) }],
    structuredContent: { plans: PLANS, currency: "BAM", payment: "PayPal (EUR)" }
  })
});

// src/lib/mcp/tools/list-legal-documents.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var CATEGORIES = {
  standard: {
    label: "Standardne izjave",
    documents: [
      "Izjava o poklonu",
      "Izjava o prebivali\u0161tu",
      "Izjava o identitetu",
      "Izjava o dostavi",
      "Izjava o vlasni\u0161tvu",
      "Izjava o smrti"
    ]
  },
  business: {
    label: "Poslovne i radne",
    documents: ["Poslovna izjava", "Radni odnos"]
  },
  personal: {
    label: "Li\u010Dne i finansijske",
    documents: ["Porodica", "Finansije"]
  },
  commercial: {
    label: "Komercijalne",
    documents: ["Kupoprodaja"]
  }
};
var list_legal_documents_default = defineTool3({
  name: "list_legal_documents",
  title: "List available legal documents",
  description: "Returns the BiH-compliant legal statement templates available in the 'Pravni dokumenti' section, grouped by category. All PDFs are generated client-side (privacy-first).",
  inputSchema: {
    category: z2.enum(["standard", "business", "personal", "commercial"]).optional().describe("Optional. Restrict to a single category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const payload = category ? { [category]: CATEGORIES[category] } : CATEGORIES;
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { categories: payload }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bh-konver-mcp",
  title: "BH KONVER MCP",
  version: "0.1.0",
  instructions: "Read-only tools for BH KONVER, a Bosnia & Herzegovina file-conversion and legal-document platform. Use `list_supported_formats` to discover which file types can be converted, `get_pricing_plans` for premium plan pricing in BAM, and `list_legal_documents` for available BiH-compliant legal statement templates.",
  tools: [list_supported_formats_default, get_pricing_plans_default, list_legal_documents_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
